site_name: mkdocs-print-site-plugin Docs
repo_url: https://github.com/timvink/mkdocs-print-site-plugin
site_url: https://timvink.github.io/mkdocs-print-site-plugin/
site_description: MkDocs Plugin allowing your site visitors to *File > Print > Save as PDF* the entire site.
site_author: Tim Vink
copyright: Copyright &copy; 2020 Maintained by <a href="https://github.com/timvink">Tim Vink</a>.

use_directory_urls: false

plugins:
    - print-site
    - search
 
nav:
    - Home: index.md
    - Options: options.md
    - Demo Content: demo_content.md
    - Contributing: contributing.md

theme:
    name: material
    font:
        text: Ubuntu
        code: Ubuntu Mono
    palette:
        primary: indigo
        accent: blue

markdown_extensions:
    - codehilite
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.highlight:
        use_pygments: true
    - toc:
        permalink: true