site_name: Documentation mkdocs-print-site-plugin
repo_url: https://github.com/timvink/mkdocs-print-site-plugin
site_url: https://timvink.github.io/mkdocs-print-site-plugin/
site_description: MkDocs Plugin allowing your site visitors to *File > Print > Save as PDF* the entire site.
site_author: Tim Vink
copyright: Copyright &copy; 2020 Maintained by <a href="https://github.com/timvink">Tim Vink</a>.

use_directory_urls: false

plugins:
    - search
    - print-site:
        add_to_navigation: true
        add_full_urls: false
        add_table_of_contents: true
        toc_title: "Table of Contents"
        toc_depth: 2
        add_full_urls: false
        enumerate_headings: true
        enumerate_figures: true
        add_cover_page: true
        path_to_pdf: "assets/site.pdf"

nav:
    - Home: index.md
    - Options: options.md
    - Customization:
        - customization/print_button.md
        - customization/pdf_button.md
        - customization/cover_page.md
        - customization/do_not_print.md
    - Demo Content: demo_content.md
    - Contributing: contributing.md

theme:
    name: material
    custom_dir: docs/overrides
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: blue
          accent: blue
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: blue
          accent: blue

markdown_extensions:
    - codehilite:
        linenums: false
        guess_lang: false
    - attr_list
    - def_list
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.snippets
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.critic:
        mode: view
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tasklist:
        clickable_checkbox: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - toc:
        permalink: ↵

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
